# Generated by Django 6.0 on 2026-02-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('com', models.JSONField(default=list)),
                ('img', models.ImageField(blank=True, null=True, upload_to='sim_images/')),
            ],
        ),
    ]
