# Generated by Django 6.0 on 2026-02-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_sim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sim',
        ),
    ]
