# Generated by Django 6.0 on 2026-02-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0003_delete_sim'),
    ]

    operations = [
        migrations.CreateModel(
            name='sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='sim_images/')),
                ('con', models.JSONField(default=list)),
                ('resp', models.JSONField(default=list)),
            ],
        ),
    ]
