# Generated by Django 6.0 on 2026-02-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0004_sim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sim',
        ),
    ]
