# Generated by Django 6.0 on 2026-02-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0005_delete_sim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('respo', models.TextField()),
            ],
        ),
    ]
