# Generated by Django 6.0 on 2026-02-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0006_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='sim_images/'),
        ),
    ]
