# Generated by Django 6.0 on 2026-02-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0007_sim_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='respo',
            field=models.JSONField(default=list),
        ),
    ]
