# Generated by Django 6.0 on 2026-02-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0008_alter_sim_respo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
