# Generated by Django 6.0 on 2026-02-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0010_remove_sim_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
